### ISSUE TITLE
Fix memory leaks in bpftrace

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1047]
If you run a trivial bpftrace script with ASAN on (see #1046), you'll see ~34 memory leaks: http://ix.io/2628 .

Build with asan by:
```
$ cd ~/dev/bpftrace
$ mkdir build && cd build
$ cmake .. -DBUILD_ASAN && make -j4
$ sudo ./src/bpftrace -e 'BEGIN { printf("hello\n"); }'
[...]
```

I'm sure we can find a lot more by running some of the scripts in `tools/` under asan mode.

**Comment by rockdaboot** [comment]
BTW, cmake 3.15.4 on Debian unstable needs `cmake .. -DBUILD_ASAN=1`.

I struggled a bit since I'm normally not using cmake :-)

**Comment by markdrayton** [comment]
Almost all of the leaks in the mentioned paste (and now, when I retry) are from parsing the program code. Presumably fixing them requires some Bison tinkering to `delete` all the stuff created with `new`. This looks tricky. The others:

```
$ sudo ./src/bpftrace -e 'BEGIN { printf("hello\n"); }' 2> /tmp/o
Attaching 1 probe...
hello
^C

$ awk 'BEGIN { RS = "\n\n"; ORS = RS } !/::parse/' /tmp/o


=================================================================
==36689==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1691 byte(s) in 329 object(s) allocated from:
    #0 0x7f034e8dd459 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f0348ff2e3c  (/usr/lib/libclang.so.10+0x3cde3c)

Direct leak of 576 byte(s) in 8 object(s) allocated from:
    #0 0x7f034e8dd639 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f034dc90fa8 in perf_reader_new /home/mark/code/bcc/src/cc/perf_reader.c:57
    #2 0x7f034dc9075d in bpf_open_perf_buffer /home/mark/code/bcc/src/cc/libbpf.c:1216
    #3 0x55ba6aece22e in bpftrace::BPFtrace::setup_perf_events() /home/mark/code/bpftrace/src/bpftrace.cpp:1076
    #4 0x55ba6aecc769 in bpftrace::BPFtrace::run(std::unique_ptr<bpftrace::BpfOrc, std::default_delete<bpftrace::BpfOrc> >) /home/mark/code/bpftrace/src/bpftrace.cpp:962
    #5 0x55ba6afb1573 in main /home/mark/code/bpftrace/src/main.cpp:805
    #6 0x7f034332e001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)

Direct leak of 15 byte(s) in 1 object(s) allocated from:
    #0 0x7f034e885a69 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cpp:452
    #1 0x7f034bc6f2ed in bcc_resolve_symname /home/mark/code/bcc/src/cc/bcc_syms.cc:728
    #2 0x55ba6ae246b6 in resolve_offset /home/mark/code/bpftrace/src/attached_probe.cpp:328
    #3 0x55ba6ae27f33 in bpftrace::AttachedProbe::resolve_offset_uprobe(bool) /home/mark/code/bpftrace/src/attached_probe.cpp:452
    #4 0x55ba6ae2b8c4 in bpftrace::AttachedProbe::attach_uprobe(bool) /home/mark/code/bpftrace/src/attached_probe.cpp:698
    #5 0x55ba6ae211bd in bpftrace::AttachedProbe::AttachedProbe(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long>, bool) /home/mark/code/bpftrace/src/attached_probe.cpp:152
    #6 0x55ba6af09200 in std::_MakeUniq<bpftrace::AttachedProbe>::__single_object std::make_unique<bpftrace::AttachedProbe, bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, bool&>(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, bool&) /usr/include/c++/10.1.0/bits/unique_ptr.h:961
    #7 0x55ba6aecba0b in bpftrace::BPFtrace::attach_probe(bpftrace::Probe&, bpftrace::BpfOrc const&) /home/mark/code/bpftrace/src/bpftrace.cpp:905
    #8 0x55ba6aecc460 in bpftrace::BPFtrace::run_special_probe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bpftrace::BpfOrc const&, void (*)()) /home/mark/code/bpftrace/src/bpftrace.cpp:950
    #9 0x55ba6aecc9d4 in bpftrace::BPFtrace::run(std::unique_ptr<bpftrace::BpfOrc, std::default_delete<bpftrace::BpfOrc> >) /home/mark/code/bpftrace/src/bpftrace.cpp:980
    #10 0x55ba6afb1573 in main /home/mark/code/bpftrace/src/main.cpp:805
    #11 0x7f034332e001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)

SUMMARY: AddressSanitizer: 4824 byte(s) leaked in 368 allocation(s).
```

The perf readers are leaked because there's no cleanup for them (should be easy to add), and the `bcc_resolve_symname` one is a legit omission and easy to fix. I haven't found any other leaks by trying the scripts in tools/ but will look more.

**Comment by oazizi000** [comment]
I have run into the same issues. Currently seeing three classes of memory leaks, similar to what @markdrayton noticed. 
1) Missing perf reader clean-up.
2) Bison leak.
3) A small leak in clang parser.

I have have fixes for all three locally, and plan to contribute them back.

#1515 is a fix for the last one, and is very simple.

The bison leak fix is much larger. I hope to submit that one for feedback soon too.

**Comment by vladdy** [comment]
@oazizi000  I'll assign this issues to you, then.

**Comment by vladdy** [comment]
ouch sorry, I thought this was assigned to me. nvm =)

**Comment by markdrayton** [comment]
@oazizi000 great! I noticed your list doesn't include the fix for leaked symbol module names. If you don't already have a fix for this ready I'll make a PR for https://github.com/markdrayton/bpftrace/commit/a34c3e8dabc66fadf9ee722ca004a5278f2ef374 (a trivial fix).

**Comment by oazizi000** [comment]
@markdrayton I hadn't run into that one yet, so go for it. It'll be great to have that in as well, since I'm sure I'd run into it eventually too.

**Comment by oazizi000** [comment]
Another simple one here: https://github.com/iovisor/bpftrace/pull/1516. This is for the perf buffer clean-up.

**Comment by viktormalik** [comment]
There are no more memleaks for the current master and we're running ASAN builds as a part of our CI (#1920).
