### ISSUE TITLE
Cannot find go symbols

### ISSUE THREAD

**Issue by kstenerud** [iovisor/bpftrace#1098]
Is there a way to use symbols that have parentheses and such?

```
# objdump -tT web_db |grep -i sql
...
00000000004da4f0 g     F .text	00000000000001c2              database/sql.(*DB).query
...
```

```
# bpftrace -e 'uretprobe:web_db:database/sql.(*DB).query { printf("X\n"); }'
stdin:1:1-32: ERROR: syntax error, unexpected (, expecting builtin or identifier
uretprobe:web_db:database/sql.(*DB).query { printf("X\n"); }
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fbs** [comment]
Quoting the function should work, i.e.: `uretprobe:web_db:"database/sql.(*DB).query" { printf("X\n"); }`

We should put this in the refernec guide somewhere. We could add a probe section under [language](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#language) or under the [uprobe](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#3-uprobeuretprobe-dynamic-tracing-user-level) section. What do you think @kstenerud

**Comment by kstenerud** [comment]
Yup, that would definitely help!

Unfortunately, I still can't seem to get it working:

```
# bpftrace -e 'uretprobe:web_db:"database/sql.(*DB).query" { printf("X\n"); }'
Attaching 1 probe...
Could not resolve symbol: web_db:database/sql.(*DB).query
```

Do I need to do something special for go programs?

```
# objdump -tT web_db |grep -i sql|grep query
0000000000867940 g     O .rodata	0000000000000078              database/sql.(*DB).queryDC.stkobj
00000000004da4f0 g     F .text	00000000000001c2              database/sql.(*DB).query
00000000004da6c0 g     F .text	00000000000007f8              database/sql.(*DB).queryDC
00000000004dce30 g     F .text	000000000000028c              database/sql.(*DB).queryDC.func1
00000000004dd0c0 g     F .text	00000000000000df              database/sql.(*DB).queryDC.func2
```

**Comment by kstenerud** [comment]
Hmm, this seems to be a much deeper problem:

```
# bpftrace -e 'uretprobe:web_db:main* { printf("X\n"); }'
Attaching 17 probes...
Could not resolve symbol: web_db:main.runAsServer.func3
```

**Comment by fbs** [comment]
can you try `./web_db` instead of `web_db` ? Looking at the bcc source:

https://github.com/iovisor/bcc/blob/master/src/cc/bcc_syms.cc#L726-L730

And our  call is `bcc_resolve_symname(path.c_str(), symbol.c_str(), loc, 0, nullptr, &bcc_sym)`. `path` is `web_db`. As there is no `/` in that it seems to think it is an shared object.

**Comment by kstenerud** [comment]
Oh yes, adding ./ worked! So this works:

```
# bpftrace -e 'uretprobe:./web_db:"database/sql.(*DB).query" { printf("X\n"); }'
Attaching 1 probe...
```

But now, if bftrace is running, the app crashes with an illegal instruction:

```
2020/01/22 15:47:23 Serving HTTP clients on 127.0.0.1:8080...
SIGILL: illegal instruction
PC=0x7fffffffe001 m=3 sigcode=128

goroutine 11 [running]:
runtime: unknown pc 0x7fffffffe001
stack: frame={sp:0xc0000e1a58, fp:0x0} stack=[0xc0000e0000,0xc0000e2000)
000000c0000e1958:  0000000000000000  000000c0000e18e0 
000000c0000e1968:  000000c0000e18d0  0000000000863ec0 
000000c0000e1978:  000000c0000140d8  00007f0b54730110 
000000c0000e1988:  000000c0000c0b00  0000000000000000 
000000c0000e1998:  0000000000000000  00000000007e2a41 
000000c0000e19a8:  0000000000000013  000000c0000e18b0 
000000c0000e19b8:  000000c0000e1a48  00000000004da626 <database/sql.(*DB).query+310> 
000000c0000e19c8:  000000c0000fc180  0000000000863ec0 
000000c0000e19d8:  000000c0000140d8  0000000000000000 
000000c0000e19e8:  0000000000000000  000000c0000e6900 
000000c0000e19f8:  000000c00005d390  00000000007e2a41 
000000c0000e1a08:  0000000000000013  0000000000000000 
000000c0000e1a18:  0000000000000000  0000000000000000 
000000c0000e1a28:  000000c0000e6b80  0000000000000000 
000000c0000e1a38:  0000000000000000  000000c0000e6900 
000000c0000e1a48:  000000c0000e1ad8  00007fffffffe000 
000000c0000e1a58: <000000c0000fc180  0000000000863ec0 
000000c0000e1a68:  000000c0000140d8  00000000007e2a41 
000000c0000e1a78:  0000000000000013  0000000000000000 
000000c0000e1a88:  0000000000000000  0000000000000000 
000000c0000e1a98:  000000000085d601  000000c0000e6b80 
000000c0000e1aa8:  0000000000000000  0000000000000000 
000000c0000e1ab8:  0000000000000000  000000c0000e1ae8 
000000c0000e1ac8:  00000000004b337d <internal/poll.(*FD).decref+45>  0000000000000008 
000000c0000e1ad8:  000000c0000e1b40  0000000000713740 <main.(*Store).DeleteAllWidgets+112> 
000000c0000e1ae8:  000000c0000fc180  0000000000863ec0 
000000c0000e1af8:  000000c0000140d8  00000000007e2a41 
000000c0000e1b08:  0000000000000013  0000000000000000 
000000c0000e1b18:  0000000000000000  0000000000000000 
000000c0000e1b28:  000000c0000e1af8  00000000004b3ad7 <internal/poll.setDeadlineImpl+215> 
000000c0000e1b38:  0000000000000000  000000c0000e1b80 
000000c0000e1b48:  00000000007160aa <main.runAsServer.func3+42>  000000c0000a2690 
runtime: unknown pc 0x7fffffffe001
stack: frame={sp:0xc0000e1a58, fp:0x0} stack=[0xc0000e0000,0xc0000e2000)
000000c0000e1958:  0000000000000000  000000c0000e18e0 
000000c0000e1968:  000000c0000e18d0  0000000000863ec0 
000000c0000e1978:  000000c0000140d8  00007f0b54730110 
000000c0000e1988:  000000c0000c0b00  0000000000000000 
000000c0000e1998:  0000000000000000  00000000007e2a41 
000000c0000e19a8:  0000000000000013  000000c0000e18b0 
000000c0000e19b8:  000000c0000e1a48  00000000004da626 <database/sql.(*DB).query+310> 
000000c0000e19c8:  000000c0000fc180  0000000000863ec0 
000000c0000e19d8:  000000c0000140d8  0000000000000000 
000000c0000e19e8:  0000000000000000  000000c0000e6900 
000000c0000e19f8:  000000c00005d390  00000000007e2a41 
000000c0000e1a08:  0000000000000013  0000000000000000 
000000c0000e1a18:  0000000000000000  0000000000000000 
000000c0000e1a28:  000000c0000e6b80  0000000000000000 
000000c0000e1a38:  0000000000000000  000000c0000e6900 
000000c0000e1a48:  000000c0000e1ad8  00007fffffffe000 
000000c0000e1a58: <000000c0000fc180  0000000000863ec0 
000000c0000e1a68:  000000c0000140d8  00000000007e2a41 
000000c0000e1a78:  0000000000000013  0000000000000000 
000000c0000e1a88:  0000000000000000  0000000000000000 
000000c0000e1a98:  000000000085d601  000000c0000e6b80 
000000c0000e1aa8:  0000000000000000  0000000000000000 
000000c0000e1ab8:  0000000000000000  000000c0000e1ae8 
000000c0000e1ac8:  00000000004b337d <internal/poll.(*FD).decref+45>  0000000000000008 
000000c0000e1ad8:  000000c0000e1b40  0000000000713740 <main.(*Store).DeleteAllWidgets+112> 
000000c0000e1ae8:  000000c0000fc180  0000000000863ec0 
000000c0000e1af8:  000000c0000140d8  00000000007e2a41 
000000c0000e1b08:  0000000000000013  0000000000000000 
000000c0000e1b18:  0000000000000000  0000000000000000 
000000c0000e1b28:  000000c0000e1af8  00000000004b3ad7 <internal/poll.setDeadlineImpl+215> 
000000c0000e1b38:  0000000000000000  000000c0000e1b80 
000000c0000e1b48:  00000000007160aa <main.runAsServer.func3+42>  000000c0000a2690 
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f0b5472fec8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000e6a18, 0x72, 0x0, 0x0, 0x7de312)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000e6a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0000e6a00, 0xc00012dbc8, 0x684034, 0xc0001360a0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000fd00, 0x5e286084, 0xc00012dbc8, 0x47bef6)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000fd00, 0xc00012dc18, 0x18, 0xc000000180, 0x6839e4)
	/usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc000136000, 0x8632c0, 0xc00000fd00, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc000136000, 0xc000136000, 0xc00012de98)
	/usr/local/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3081
main.runAsServer()
	/home/karl/work/code/profiler-demo-apps/go/web-db/main.go:243 +0x7fd
main.main()
	/home/karl/work/code/profiler-demo-apps/go/web-db/main.go:359 +0x409

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [select]:
database/sql.(*DB).connectionOpener(0xc0000fc180, 0x863e80, 0xc000024b80)
	/usr/local/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:722 +0x15d

goroutine 10 [select]:
database/sql.(*DB).connectionResetter(0xc0000fc180, 0x863e80, 0xc000024b80)
	/usr/local/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:723 +0x193

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7f0b5472fdf8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000e6a98, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000e6a80, 0xc000091b41, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0000e6a80, 0xc000091b41, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000100e0, 0xc000091b41, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc000091b30)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

rax    0xc0000e6b80
rbx    0x0
rcx    0x0
rdx    0x0
rdi    0xc0000e6b80
rsi    0x78
rbp    0xc0000e1ad8
rsp    0xc0000e1a58
r8     0x7f0b55f8535f
r9     0x203000
r10    0x2
r11    0x11
r12    0xf1
r13    0x0
r14    0x85180a
r15    0x0
rip    0x7fffffffe001
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
```

**Comment by fbs** [comment]
Oh woops, missed that you use uretprobes. Go doesn't like them (see #970). We don't have a good solution yet. The best you can do is to install uprobes on all interesting exit points, which is a bit tedious.

**Comment by danobi** [comment]
I think the original question has been resolved.
