### ISSUE TITLE
bpftrace crashes during finalization with specific one-liner (probably related to lhist function)

### ISSUE THREAD

**Issue by caringi** [iovisor/bpftrace#201]
The following one-liner works but crashes during finalization:

    bpftrace -e 'kretprobe:vfs_read { @bytes = lhist(retval, 0, 2000, 200); }'

Output:

    Attaching 1 probe...
    ^C

    @bytes: 
    (...,0M]             858 |@@@@@@                                              |
    [0M, 200)           6801 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
    [200, 400)             4 |                                                    |
    [400, 600)             8 |                                                    |
    [600, 800)             7 |                                                    |
    [800, 1000)            0 |                                                    |
    [1000, 1200)         155 |@                                                   |
    [1200, 1400)          14 |                                                    |
    [1400, 1600)           0 |                                                    |
    [1600, 1800)           0 |                                                    |
    [1800, 2000)           0 |                                                    |
    [2000,...)            14 |                                                    |

    free(): invalid size
    Aborted (core dumped)

Backtrace:

    #0  0x00007fa7cfe6eeab in raise () from /lib64/libc.so.6
    #1  0x00007fa7cfe595b9 in abort () from /lib64/libc.so.6
    #2  0x00007fa7cfeb17b7 in __libc_message () from /lib64/libc.so.6
    #3  0x00007fa7cfeb7c4c in malloc_printerr () from /lib64/libc.so.6
    #4  0x00007fa7cfeb93dc in _int_free () from /lib64/libc.so.6
    #5  0x000000000058a990 in __gnu_cxx::new_allocator<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> > >::deallocate (this=0x7ffd2ddff310, __p=0x17101b0) at /usr/include/c++/8/ext/new_allocator.h:125
    #6  0x00000000005882d6 in std::allocator_traits<std::allocator<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> > > >::deallocate (__a=..., __p=0x17101b0, __n=1) at /usr/include/c++/8/bits/alloc_traits.h:462
    #7  0x0000000000584110 in std::_Vector_base<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> >, std::allocator<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> > > >::_M_deallocate (this=0x7ffd2ddff310, 
    __p=0x17101b0, __n=1) at /usr/include/c++/8/bits/stl_vector.h:304
    #8  0x00000000005810ea in std::_Vector_base<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> >, std::allocator<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> > > >::~_Vector_base (this=0x7ffd2ddff310, 
    __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:285
    #9  0x000000000057e889 in std::vector<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> >, std::allocator<std::unique_ptr<bpftrace::AttachedProbe, std::default_delete<bpftrace::AttachedProbe> > > >::~vector (this=0x7ffd2ddff310, 
    __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:570
    #10 0x000000000057dfc4 in bpftrace::BPFtrace::~BPFtrace (this=0x7ffd2ddff1f0, __in_chrg=<optimized out>)
    at /home/acaringi/devel/bpftrace_upstream/src/bpftrace.h:53
    #11 0x00000000005972c2 in main (argc=3, argv=0x7ffd2ddff5b8) at /home/acaringi/devel/bpftrace_upstream/src/main.cpp:142

**Comment by caringi** [comment]
Fixed... https://github.com/iovisor/bpftrace/pull/256

Closing it.
