### ISSUE TITLE
bfptrace  segmentation fault on debian11

### ISSUE THREAD

**Issue by selfboot** [iovisor/bpftrace#2201]
I compile bcc and bpftrace on debian11, bcc works fine. But when i run any bpftrace command, just segmentation fault.

```
bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
Attaching 1 probe...
[1]    272138 segmentation fault  bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
```

## GDB info

```
(gdb) run bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
Starting program: /usr/local/bin/bpftrace bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 272574]
[New Thread 0x7fffee1bc700 (LWP 272576)]
[Thread 0x7fffee1bc700 (LWP 272576) exited]
[New Thread 0x7fffee1bc700 (LWP 272577)]
[New Thread 0x7fffee1bc700 (LWP 272581)]
[Thread 0x7fffee1bc700 (LWP 272577) exited]
[New Thread 0x7fffee1bc700 (LWP 272584)]
[Thread 0x7fffee1bc700 (LWP 272581) exited]
[Thread 0x7fffee1bc700 (LWP 272584) exited]
[New Thread 0x7fffee1bc700 (LWP 272585)]
[Thread 0x7fffee1bc700 (LWP 272585) exited]
[New Thread 0x7fffee1bc700 (LWP 272586)]
[Thread 0x7fffee1bc700 (LWP 272586) exited]
Attaching 1 probe...

Thread 1 "bpftrace" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb)
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff0d14f76 in __vfprintf_internal (s=s@entry=0x7fffffff9cb0, format=0x7ffff7fb23e6 "libbpf: loading %s\n",
    ap=0x7fffffffc350, mode_flags=0) at vfprintf-internal.c:1688
#2  0x00007ffff0d15f44 in buffered_vfprintf (s=s@entry=0x7ffff0e685c0 <_IO_2_1_stderr_>,
    format=format@entry=0x7ffff7fb23e6 "libbpf: loading %s\n", args=args@entry=0x7fffffffc350,
    mode_flags=mode_flags@entry=0) at vfprintf-internal.c:2377
#3  0x00007ffff0d130d4 in __vfprintf_internal (s=0x7ffff0e685c0 <_IO_2_1_stderr_>,
    format=0x7ffff7fb23e6 "libbpf: loading %s\n", ap=0x7fffffffc350, mode_flags=0) at vfprintf-internal.c:1346
#4  0x00007ffff7f984fb in ?? () from /lib/x86_64-linux-gnu/libbpf.so.0
#5  0x00007ffff7fa4c28 in bpf_object.open_xattr () from /lib/x86_64-linux-gnu/libbpf.so.0
#6  0x00007ffff7fa98ad in bpf_prog_load_xattr () from /lib/x86_64-linux-gnu/libbpf.so.0
#7  0x00007ffff7fa9a93 in bpf_prog_load () from /lib/x86_64-linux-gnu/libbpf.so.0
#8  0x00007ffff7b3ed60 in libbpf_bpf_prog_load () from /lib/x86_64-linux-gnu/libbcc_bpf.so.0
#9  0x00007ffff7b40216 in bcc_prog_load_xattr () from /lib/x86_64-linux-gnu/libbcc_bpf.so.0
#10 0x00005555555f3a34 in bpftrace::AttachedProbe::load_prog() ()
#11 0x00005555555f719c in bpftrace::AttachedProbe::AttachedProbe(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long>, bool) ()
#12 0x0000555555610f98 in bpftrace::BPFtrace::attach_probe(bpftrace::Probe&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned char, std::allocator<unsigned char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned char, std::allocator<unsigned char> > > > >&) ()
#13 0x0000555555613519 in bpftrace::BPFtrace::run(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned char, std::allocator<unsigned char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned char, std::allocator<unsigned char> > > > >) ()
#14 0x0000555555599b04 in main ()
(gdb) info registers
rax            0x18                24
rbx            0x0                 0
rcx            0x2                 2
rdx            0x2                 2
rsi            0x7fffffff9c48      140737488329800
rdi            0x2                 2
rbp            0x7fffffff9c80      0x7fffffff9c80
rsp            0x7fffffff9728      0x7fffffff9728
r8             0xffffffff          4294967295
r9             0x10                16
r10            0x2                 2
r11            0x0                 0
r12            0x7fffffff9cb0      140737488329904
r13            0x7ffff7fb23e6      140737353819110
r14            0x7fffffffc350      140737488339792
r15            0x73                115
rip            0x7ffff0e08b71      0x7ffff0e08b71 <__strlen_avx2+17>
eflags         0x10287             [ CF PF SF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

<img width="963" alt="image" src="https://user-images.githubusercontent.com/2769831/165080380-52d2fdfa-103f-482d-ac37-75d5d8558058.png">

## bpftrace --info
System
  OS: Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07)
  Arch: x86_64

Build
  version: v0.14.0-108-ge05e
  LLVM: 11.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): yes

**Comment by selfboot** [comment]
Recompile with llvm12, same problem.

```
bpftrace --info
System
  OS: Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07)
  Arch: x86_64

Build
  version: v0.14.0-108-ge05e
  LLVM: 12.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): yes
```

**Comment by viktormalik** [comment]
Thanks for reporting! There seems to be a bug when building against BCC >= 0.24.0, I was able to reproduce on Fedora 35, too. For now, you can bypass this by compiling against BCC 0.23.0 (or lower) and I'll try to discover the problem.

**Comment by selfboot** [comment]
I compile  BCC 0.23.0, bpftrace it woks fine, thank you very much!

**Comment by viktormalik** [comment]
This is a duplicate of #2173, closing now.
