### ISSUE TITLE
SyntaxError: LIBBCC_BPF_CONTAINS_RUNTIME = bool(@LIBBCC_BPF_CONTAINS_RUNTIME@)

### ISSUE THREAD

**Issue by vt-alt** [iovisor/bpftrace#2245]
### What reproduces the bug?
While building a package for ALT Linux we run `tests/runtime-tests.sh` and it fails with:
```
====================
bpftrace --info:
====================
System
  OS: Linux 5.17.11-un-def-alt1 #1 SMP PREEMPT Wed May 25 18:26:15 UTC 2022
  Arch: x86_64

Build
  version: v0.15.0
  LLVM: 13.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/bpftrace-0.15.0/tests/runtime/engine/main.py", line 9, in <module>
    from runner import Runner, ok, fail, warn
  File "/usr/src/RPM/BUILD/bpftrace-0.15.0/tests/runtime/engine/runner.py", line 13, in <module>
    import cmake_vars
  File "/usr/src/RPM/BUILD/bpftrace-0.15.0/tests/runtime/engine/cmake_vars.py", line 1
    LIBBCC_BPF_CONTAINS_RUNTIME = bool(@LIBBCC_BPF_CONTAINS_RUNTIME@)
                                       ^
SyntaxError: invalid syntax
```

It seems that `@LIBBCC_BPF_CONTAINS_RUNTIME@` is not expanded in `cmake_vars.py` by the build system.

**Comment by viktormalik** [comment]
Sadly, I cannot reproduce. Building on Alt Sisyphus with CMake 3.23.2 generates the file correctly.

Are you running `tests/runtime-tests.sh` from the build directory?

**Comment by jordalgo** [comment]
Closing due to inactivity.

**Comment by matthew-olson-intel** [comment]
I'm actually getting this error now, as well. Investigating.

**Comment by matthew-olson-intel** [comment]
Testing all recent commits related to this, it seems to be coming from this:
https://github.com/iovisor/bpftrace/commit/54d6b53e83fd33904116704e8c350741a7ba57aa

This commit removes the call to `configure_file`, which [substitutes variable values](https://cmake.org/cmake/help/latest/command/configure_file.html). It looks like this commit replaces that with globbing and copying, but I don't think those forms [substitute variable values](https://cmake.org/cmake/help/latest/command/file.html#glob). From a quick glance, we might be able to use `file(CONFIGURE OUTPUT...)` to fix this.

**Comment by matthew-olson-intel** [comment]
I've also determined that it only happens when I use the `Ninja` generator; if I generate normal Makefiles, it doesn't happen.

**Comment by vt-alt** [comment]
The thing is still unfixed in `0.21.0`.

**Comment by ajor** [comment]
@vt-alt Since we can't reproduce it ourselves, would you be able to provide some debug logs please? With a fresh (empty) build directory, it'd be useful to get the outputs of two runs of CMake with both `--trace` and `--trace-expand`:
```
cmake ${PATH_TO_BPFTRACE_SOURCE} --trace &> trace.txt
rm -rf * # clear the build directory before the second run
cmake ${PATH_TO_BPFTRACE_SOURCE} --trace-expand &> trace-expand.txt
```

(if there's a way to get both `--trace` and `--trace-expand` in a single run, that'd do instead)

**Comment by vt-alt** [comment]
Thanks for the reply! I found the cause - I was building `-DBUILD_TESTING=OFF` but running the tests (from the source root, and many of them worked). After I removed `BUILD_TESTING=OFF` expansion worked OK (and I run the tests from the build dir now).

ps. Just want to add a note

> (if there's a way to get both `--trace` and `--trace-expand` in a single run, that'd do instead)

I did not understand the suggestion - aren't `--trace-expand` is the same as `--trace` but with expansion? So, how they could or cannot be together? So this was a bit confusing.

**Comment by ajor** [comment]
> ps. Just want to add a note
> 
> > (if there's a way to get both `--trace` and `--trace-expand` in a single run, that'd do instead)
> 
> I did not understand the suggestion - aren't `--trace-expand` is the same as `--trace` but with expansion? So, how they could or cannot be together? So this was a bit confusing.

`--trace` shows all the CMake commands which are executed (it shows them in exactly the format they're written in CMakeLists.txt). `--trace-expand` also shows commands, but replaces the names of CMake variables with their values. I haven't managed to find a way to get CMake to show both a variable's name and its value in a single run, but maybe I'm missing something.

**Comment by vt-alt** [comment]
@ajor Thanks for explanation. Perhaps, there is no feature like this in CMake.
