### ISSUE TITLE
segfault on wsl2

### ISSUE THREAD

**Issue by jmikedupont2** [iovisor/bpftrace#2288]
With the latest version (on debian experimental in wsl2)
and latest version of llvm

### What reproduces the bug?
```
 /usr/local/bin/bpftrace -lv uprobe:/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1:_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE
Segmentation fault
```

### bpftrace --info
```System
  OS: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
  Arch: x86_64

Build
  version: v0.15.0-52-g9f515
  LLVM: 13.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): yes

Segmentation fault```

**Comment by jmikedupont2** [comment]
Debug the --info
command

```
(gdb) r --info
Starting program: /usr/local/bin/bpftrace --info
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
System
  OS: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
  Arch: x86_64

Build
  version: v0.15.0-52-g9f515
  LLVM: 13.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): yes


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f685e0 in btf.type_cnt () from /usr/lib/x86_64-linux-gnu/libbpf.so.0
(gdb) bt
#0  0x00007ffff7f685e0 in btf.type_cnt () from /usr/lib/x86_64-linux-gnu/libbpf.so.0
#1  0x00007ffff7f69f48 in ?? () from /usr/lib/x86_64-linux-gnu/libbpf.so.0
#2  0x0000555555632204 in bpftrace::BTF::get_btf_id (this=0x7fffffffab88, name="dentry_open") at /root/experiments2/bpftrace/src/btf.cpp:751
#3  0x00005555555f0783 in bpftrace::BPFfeature::try_load (this=0x7fffffffab40, prog_type=libbpf::BPF_PROG_TYPE_TRACING, insns=0x7fffffffa720, len=10, name=0x5555557b00f2 "dentry_open",
    attach_type=std::optional<libbpf::bpf_attach_type> = {...}) at /root/experiments2/bpftrace/src/bpffeature.cpp:98
#4  0x00005555555f13cf in bpftrace::BPFfeature::has_d_path (this=0x7fffffffab40) at /root/experiments2/bpftrace/src/bpffeature.cpp:345
#5  0x00005555555f1d21 in bpftrace::BPFfeature::report[abi:cxx11]() (this=0x7fffffffab40) at /root/experiments2/bpftrace/src/bpffeature.cpp:507
#6  0x00005555555793ad in info () at /root/experiments2/bpftrace/src/main.cpp:179
#7  0x000055555557b338 in parse_args (argc=2, argv=0x7fffffffe4d8) at /root/experiments2/bpftrace/src/main.cpp:503
#8  0x000055555557c15a in main (argc=2, argv=0x7fffffffe4d8) at /root/experiments2/bpftrace/src/main.cpp:695
```

**Comment by jmikedupont2** [comment]
And debugging the crash itself 
```
(gdb) r -lv uprobe:/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1:_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE
Starting program: /usr/local/bin/bpftrace -lv uprobe:/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1:_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11ra\
w_ostreamE
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff02367c0 in std::char_traits<char>::length (__s=0x0) at /build/gcc-12-UvIqNI/gcc-12-12.1.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (this=0x7fffffffb360, __s=0x0)
    at /build/gcc-12-UvIqNI/gcc-12-12.1.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:893
#3  0x000055555563fd13 in std::operator==<char, std::char_traits<char>, std::allocator<char> > (__lhs=0x0,
    __rhs="_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE") at /usr/include/c++/11/bits/basic_string.h:6291
#4  0x000055555563acbb in bpftrace::get_func_die_cb (func_die=0x7fffffffb218, arg=0x7fffffffb360) at /root/experiments2/bpftrace/src/dwarf_parser.cpp:49
#5  0x00007ffff7bf81a1 in ?? () from /usr/lib/x86_64-linux-gnu/libdw.so.1
#6  0x00007ffff7bf6540 in dwarf_getfuncs () from /usr/lib/x86_64-linux-gnu/libdw.so.1
#7  0x000055555563ad8f in bpftrace::Dwarf::get_func_die (this=0x555556147040,
    function="_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE") at /root/experiments2/bpftrace/src/dwarf_parser.cpp:65
#8  0x000055555563ae85 in bpftrace::Dwarf::function_param_dies (this=0x555556147040,
    function="_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE") at /root/experiments2/bpftrace/src/dwarf_parser.cpp:83
#9  0x000055555563c012 in bpftrace::Dwarf::get_function_params (this=0x555556147040,
    function="_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE") at /root/experiments2/bpftrace/src/dwarf_parser.cpp:267
#10 0x0000555555660ef2 in bpftrace::ProbeMatcher::get_uprobe_params (this=0x555555a6a660, uprobes=std::set with 1 element = {...}) at /root/experiments2/bpftrace/src/probe_matcher.cpp:416
#11 0x0000555555661354 in bpftrace::ProbeMatcher::list_probes (this=0x555555a6a660, prog=0x555555a6abf0) at /root/experiments2/bpftrace/src/probe_matcher.cpp:447
#12 0x000
```

**Comment by jmikedupont2** [comment]
The lhs is null in the comparison. 
```
#3  0x000055555563fd13 in std::operator==<char, std::char_traits<char>, std::allocator<char> > (__lhs=0x0,
    __rhs="_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE") at /usr/include/c++/11/bits/basic_string.h:6291
6291        { return __rhs.compare(__lhs) == 0; }
(gdb) p __rhs
$2 = "_ZNK12_GLOBAL__N_122X86GenericDisassembler14getInstructionERN4llvm6MCInstERmNS1_8ArrayRefIhEEmRNS1_11raw_ostreamE"
(gdb) p __lhs
$3 = 0x0
(gdb)
```

**Comment by jmikedupont2** [comment]
```
(gdb) p (char*)dwarf_diename(func_die)
$6 = 0x0
(gdb) p func_die
$7 = (Dwarf_Die *) 0x7fffffffb218
(gdb) p *func_die
$8 = {addr = 0x7fffd994f926, cu = 0x555555e9e4b8, abbrev = 0x555555e9e780, padding__ = 0}
```

**Comment by jmikedupont2** [comment]
It looks like the dwarf data is not being read properly.

**Comment by viktormalik** [comment]
Hi, I can't reproduce this but the reason seems to be that your binary contains DWARF subprogram entries which do not have a name. I tried to propose a fix [here](https://github.com/viktormalik/bpftrace/tree/dwarf-getfunc-fix), could you please give it a try?

Anyway, note that while this could remove the segfault, bpftrace still won't show the parameters of the function as the DWARF support is limited to C programs for now. I'll try to add support for C++ in future, though.

**Comment by viktormalik** [comment]
ping @jmikedupont2

**Comment by jmikedupont2** [comment]
will take a look.

**Comment by jmikedupont2** [comment]
ok I am going to close this, I am done with wsl and back to linux. also I am using perf probe now directly.
