### ISSUE TITLE
regression: segv with invalid probe names

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#231]
It looks like the fix for #12 introduced a fairly serious regression when parsing invalid probe names:

```
> gdb -q /usr/local/bin/bpftrace.new
Reading symbols from /usr/local/bin/bpftrace.new...done.
(gdb) set args -e 'bad:probe:name { exit(); }'
(gdb) run
Starting program: /usr/local/bin/bpftrace.new -e 'bad:probe:name { exit(); }'
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2db3f63 in std::string::size() const () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install devtoolset-6-elfutils-libelf-0.167-2.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff2db3f63 in std::string::size() const () from /lib64/libstdc++.so.6
#1  0x000000000051f660 in std::operator==<char> (__lhs="bad",
    __rhs=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>)
    at /opt/rh/devtoolset-6/root/usr/include/c++/6.2.1/bits/basic_string.h:5060
#2  0x000000000057dbe2 in bpftrace::probetypeName (type="bad") at /data/users/jonhaslam/bpftrace/src/types.cpp:70
#3  0x00000000005b7672 in bpftrace::ast::SemanticAnalyser::visit (this=0x7fffffffd2a0, ap=...)
    at /data/users/jonhaslam/bpftrace/src/ast/semantic_analyser.cpp:686
#4  0x00000000005800b2 in bpftrace::ast::AttachPoint::accept (this=0x8a20a0, v=...)
    at /data/users/jonhaslam/bpftrace/src/ast/ast.cpp:68
#5  0x00000000005b84c7 in bpftrace::ast::SemanticAnalyser::visit (this=0x7fffffffd2a0, probe=...)
    at /data/users/jonhaslam/bpftrace/src/ast/semantic_analyser.cpp:799
#6  0x000000000058014c in bpftrace::ast::Probe::accept (this=0x8a2200, v=...)
    at /data/users/jonhaslam/bpftrace/src/ast/ast.cpp:80
#7  0x00000000005b8612 in bpftrace::ast::SemanticAnalyser::visit (this=0x7fffffffd2a0, program=...)
    at /data/users/jonhaslam/bpftrace/src/ast/semantic_analyser.cpp:813
#8  0x0000000000580180 in bpftrace::ast::Program::accept (this=0x8a2270, v=...)
    at /data/users/jonhaslam/bpftrace/src/ast/ast.cpp:84
#9  0x00000000005b868d in bpftrace::ast::SemanticAnalyser::analyse (this=0x7fffffffd2a0)
    at /data/users/jonhaslam/bpftrace/src/ast/semantic_analyser.cpp:822
#10 0x0000000000571161 in main (argc=3, argv=0x7fffffffdb58) at /data/users/jonhaslam/bpftrace/src/main.cpp:169
```

We walk off the end of the array when we don't match a probe as 'sizeof(PROBE_LIST)' returns the size in bytes of the PROBE_LIST array and not the number of elements as was intended.

The fix is to either simply do 'sizeof(PROBE_LIST) / sizeof(*PROBE_LIST)' or, preferably, use a container type such as 'std::vector'.

Tests should also be added to catch this regression.

**Comment by mmarchini** [comment]
Fixed in #237
