### ISSUE TITLE
SIGABRT generated when args contains members with bool type

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#238]
If we try keying a map using any `args` member whose type is a`bool`  a SIGABRT is generated:

```
#  grep transport_offset_valid /sys/kernel/debug/tracing/events/net/net_dev_start_xmit/format
        field:bool transport_offset_valid;      offset:48;      size:1; signed:0;

# bpftrace -e 'tracepoint:net:net_dev_start_xmit{@[args->transport_offset_valid] = count();}'
Aborted (core dumped)
```

The top few frames:

```
(gdb) bt
#0  0x00007ffff2448277 in raise () from /lib64/libc.so.6
#1  0x00007ffff2449968 in abort () from /lib64/libc.so.6
#2  0x00000000005aa711 in bpftrace::ast::IRBuilderBPF::GetType (
    this=0x7fffffffd8b8, stype=...)
    at /data/users/jonhaslam/bpftrace/src/ast/irbuilderbpf.cpp:126
#3  0x00000000005aa409 in bpftrace::ast::IRBuilderBPF::CreateAllocaBPF (
    this=0x7fffffffd8b8, stype=..., name=...)
    at /data/users/jonhaslam/bpftrace/src/ast/irbuilderbpf.cpp:57
#4  0x000000000058a995 in bpftrace::ast::CodegenLLVM::visit (
    this=0x7fffffffd890, acc=...)
```

In we look at the `stype` struct in frame 2 we see its size is 0 which leads to the abort:

```
(gdb) p stype
$2 = (const bpftrace::SizedType &) @0x8ada78: {
  type = bpftrace::Type::none,
  size = 0,
...
```

This reason for this is because `clang_parser.cpp/get_sized_type()` is missing handling the clang `CXType_Bool` type so we default the type size to be 0.

I'll push a fix shortly.

**Comment by ajor** [comment]
Fix merged
