### ISSUE TITLE
Can't execute bcctools cachetop.

### ISSUE THREAD

**Issue by EricHChz** [iovisor/bpftrace#2529]
### What reproduces the bug?

when I use python3 cachetop -p in the Android phone, it can't execute.

### bpftrace --info

/bpftools/share/bcc/tools # python3 cachetop
Traceback (most recent call last):
  File "/data/tmp/bpftools/share/bcc/tools/cachetop", line 27, in <module>
    import curses
  File "/data/tmp/bpftools/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by fbs** [comment]
https://github.com/iovisor/bcc
