### ISSUE TITLE
zero() carnage

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#259]
There are a few problems when applying the zero() builtin to maps with different aggregating functions.

if you try and zero() a stats() or lhist() map, bpftrace hangs indefinitely in the following stack and has to be killed:

```
#  /data/users/jonhaslam/bpftrace] pstack 511616
#0  0x00007f2be37eeec9 in syscall () from /lib64/libc.so.6
#1  0x00000000005d88a9 in bpf_get_next_key ()
#2  0x000000000054b172 in bpftrace::BPFtrace::zero_map (this=0x7ffeaab78400, map=...) at /data/users/jonhaslam/bpftrace/src/bpftrace.cpp:642
#3  0x000000000054ac9a in bpftrace::BPFtrace::zero_map_ident (this=0x7ffeaab78400, ident="@s5") at /data/users/jonhaslam/bpftrace/src/bpftrace.cpp:571
#4  0x0000000000548b22 in bpftrace::perf_event_printer (cb_cookie=0x7ffeaab78400, data=0x7f2be92860e4, size=12) at /data/users/jonhaslam/bpftrace/src/bpftrace.cpp:182
#5  0x00000000005da8ce in perf_reader_event_read ()
#6  0x000000000054a8a6 in bpftrace::BPFtrace::poll_perf_events (this=0x7ffeaab78400, epollfd=11, timeout=-1) at /data/users/jonhaslam/bpftrace/src/bpftrace.cpp:501
#7  0x000000000054a55c in bpftrace::BPFtrace::run (this=0x7ffeaab78400, bpforc=std::unique_ptr<bpftrace::BpfOrc> containing 0x8c01f0) at /data/users/jonhaslam/bpftrace/src/bpftrace.cpp:442
#8  0x00000000005736b4 in main (argc=2, argv=0x7ffeaab78768) at /data/users/jonhaslam/bpftrace/src/main.cpp:199
```

If you try and print() a previously zero()'d map (obviously not stats() or lhist() because of the above) then we get garbage in the map. The following output example is from a zero'd count() map but you get the same result for max(), min() and sum() also:

```
@s1[Rocks5_0]: 421363842818265
@s1[python2]: 421363842818289
@s1[Io5_0]: 421363842818313
<chop>
```

The only map function that appears to successfully zero() is the one using the hist() function.

I'll have a fix for this shortly.

**Comment by brendangregg** [comment]
I think this was fixed by #265, closing.
