### ISSUE TITLE
bpftrace crashing in bpftrace::BPFtrace::resolve_uid() if /etc/passwd contains a blank line 

### ISSUE THREAD

**Issue by monkburger** [iovisor/bpftrace#2628]
Running the following commands will throw a crash when using the username built-in for printf:

```
sed -i.bak '/root/s/^/\n/' /etc/passwd
./bpftrace -e 'kprobe:do_nanosleep { printf("%s\n", username); }'

```

```
Attaching 1 probe...
root
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; std::vector<_Tp, _Alloc>::reference = std::__cxx11::basic_string<char>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)

```

GDB shows the following:

```
#0  0x0000555555636d19 in bpftrace::BPFtrace::resolve_uid[abi:cxx11](unsigned long) const ()
#1  0x0000555555637f01 in bpftrace::BPFtrace::get_arg_values(std::vector<bpftrace::Field, std::allocator<bpftrace::Field> > const&, unsigned char*) ()
#2  0x0000555555639596 in bpftrace::perf_event_printer(void*, void*, int) ()
#3  0x0000555555639c3d in bpftrace::ringbuf_printer(void*, void*, unsigned long) ()
#4  0x00005555556ccf9e in ringbuf_process_ring (r=0x555556bd7060) at ringbuf.c:253
#5  0x00005555556cd6dc in ring_buffer__poll (rb=0x5555559e5ff0, timeout_ms=<optimized out>) at ringbu

```

It took me a bit to track this down because nothing else on the system was crashing, but I can repo this crash on AlmaLinux 8/9, Ubuntu 20/22. Tried this with the vendor-supplied bpf packages and one from git (master)

(FWIW: I was unaware of the existence of any blank lines in /etc/passwd on the server that started showing this issue)

```

System
  OS: Linux 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023
  Arch: x86_64

Build
  version: v0.18.0-26-ga7dec
  LLVM: 14.0.0
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  iter:task_vma: yes
  kprobe_multi: no
  raw_tp_special: yes
```

**Comment by viktormalik** [comment]
Nice catch! Should be fixed by #2631.
