### ISSUE TITLE
bpftrace may crash handling anonymous structs or unions in DWARF data

### ISSUE THREAD

**Issue by rpigott** [iovisor/bpftrace#2867]
Originally reported in #2863, bpftrace may crash if DWARF data contains references to anonymous structs or unions. bpftrace fails to create a valid name for these members here:

https://github.com/iovisor/bpftrace/blob/289f0c7e028b2317aeddbb0228d542f6250fe08c/src/dwarf_parser.cpp#L183C1-L185

See #2863 for more info.

**Comment by danobi** [comment]
FWIW, when generating type definitions from BTF (similar to DWARF, but simpler), anon unions/structs get a generic anon name: https://github.com/libbpf/libbpf-rs/blob/4ef150551dbb25b18db7368cec79ca7ef9adfe0e/libbpf-cargo/src/gen/btf.rs#L72-L82

That seems like it should work? User probably will never directly reference anon record type. So as long as bpftrace doesn't barf, my feeling is that it should be ok.

@viktormalik would know better tho

**Comment by danobi** [comment]
More details here: https://github.com/libbpf/libbpf-rs/commit/fa5b28cb13e7dd94b5f01972dd0b2a4d2ae7750f

**Comment by viktormalik** [comment]
> FWIW, when libbpf-rs generates type definitions from BTF (similar to DWARF, but simpler), anon unions/structs get a generic anon name: https://github.com/libbpf/libbpf-rs/blob/4ef150551dbb25b18db7368cec79ca7ef9adfe0e/libbpf-cargo/src/gen/btf.rs#L72-L82
> 
> That seems like it should work? I can't think of any valid reasons a user would directly reference an anon record type. So as long as bpftrace doesn't barf, my feeling is that it should be ok.

Agreed. As long as the names are unique (so that different anonymous types don't override each other in the struct manager), I believe that this approach should work.

**Comment by martinetd** [comment]
I was about to open another bug for something similar (although there doesn't seem to be anonymous in the field I was accessing), but perhaps the situation on this has also improved with #5095 ?

bpftrace 0.25.1 crashes with this minimal build of swupdate
```
$ cd /tmp
$ git clone http://github.com/sbabic/swupdate
$ cd swupdate && make no_ssl_defconfig && make -j32
# bpftrace  -v -e 'uprobe:/tmp/swupdate/swupdate_unstripped:copyimage {$img = args->img; if ($img) { printf("copyimage %s\n", $img->fname ); }}'
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted (core dumped)
```
with a backtrace that ends like this:
```
(gdb) bt
...
#8  0x00007fffe90a42ea in std::__throw_logic_error(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00005555555bc8e8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) ()
#10 0x000055555572849a in bpftrace::Dwarf::get_stype(Dwarf_Die&, bool) const ()
#11 0x0000555555728d64 in bpftrace::Dwarf::resolve_fields(bpftrace::SizedType const&) const ()
#12 0x0000555555728582 in bpftrace::Dwarf::get_stype(Dwarf_Die&, bool) const ()
#13 0x0000555555728d64 in bpftrace::Dwarf::resolve_fields(bpftrace::SizedType const&) const ()
#14 0x00005555559f25d1 in bpftrace::ast::(anonymous namespace)::FieldAnalyser::resolve_fields(bpftrace::SizedType&) ()
#15 0x00005555559f1e05 in bpftrace::ast::(anonymous namespace)::FieldAnalyser::visit(bpftrace::ast::FieldAccess&) ()
#16 0x00005555559f73d7 in void bpftrace::ast::Visitor<bpftrace::ast::(anonymous namespace)::FieldAnalyser, void>::visitImpl<bpftrace::ast::FieldAccess>(bpftrace::ast::FieldAccess&) ()
#17 0x00005555559f6d6c in void bpftrace::ast::Visitor<bpftrace::ast::(anonymous namespace)::FieldAnalyser, void>::visit<bpftrace::ast::FieldAccess>(bpftrace::ast::FieldAccess*) ()
....
```

but it stopped failing on master, and I got 0.25.1 to work (at least probe attaches) after backporting e1159ca5a42b4d94efddc1826e2e2ed1d872b91e (with 68fb673f366ef99f52a4d24e012df0f2841a5239 , 4b709054af8c0e7f228e23013d9ae876ca0965b4 and eeca1ff27442a0fce3b61908d7dc9d65a311cc99 to minimize conflicts but the first commit is what fixes the abort)


Sorry if it's a different bug, but would backporting #5095 to stable branch make sense (a tad big for my liking), or is there going to be a 0.26 soon enough that it's not worth bothering?

Thanks!

**Comment by viktormalik** [comment]
@martinetd looks like a different issue to me. Could you please open a separate GitHub issue? It would be also nice if we had some minimal reproducer but I understand that it can be hard to produce. Anyways, let's follow up in a separate issue.
