### ISSUE TITLE
enum struct member missing size

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#776]
I hit this writing a more complex kernel program. Looks like enums lack a size, which can cause failures. I've included a smaller reproducer here.

```
# ./enum.bt 
0 is not a valid type size for GetType
Aborted (core dumped)
```

```
#!/usr/local/bin/bpftrace

enum MyType {
	a = 1,
	b
};

struct MyStruct {
	enum MyType t;
};

BEGIN
{
	$s = (struct MyStruct *)0;
	@[$s->t]++;
}
```

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffef922801 in __GI_abort () at abort.c:79
#2  0x00005555557ab141 in bpftrace::ast::IRBuilderBPF::GetType (this=0x7fffffffe618, stype=...)
    at /home/bgregg/Build/bpftrace/src/ast/irbuilderbpf.cpp:130
#3  0x00005555557aadb5 in bpftrace::ast::IRBuilderBPF::CreateAllocaBPF (this=0x7fffffffe618, stype=..., name="MyStruct.t")
    at /home/bgregg/Build/bpftrace/src/ast/irbuilderbpf.cpp:57
#4  0x000055555577f4b0 in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe5f0, acc=...) at /home/bgregg/Build/bpftrace/src/ast/codegen_llvm.cpp:1047
#5  0x00005555557720f4 in bpftrace::ast::FieldAccess::accept (this=0x555555af4a30, v=...) at /home/bgregg/Build/bpftrace/src/ast/ast.cpp:57
#6  0x0000555555781b78 in bpftrace::ast::CodegenLLVM::getMapKey (this=0x7fffffffe5f0, map=...)
    at /home/bgregg/Build/bpftrace/src/ast/codegen_llvm.cpp:1387
#7  0x000055555577d3cf in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe5f0, map=...) at /home/bgregg/Build/bpftrace/src/ast/codegen_llvm.cpp:771
#8  0x0000555555771ffa in bpftrace::ast::Map::accept (this=0x7fffe80d1dc0, v=...) at /home/bgregg/Build/bpftrace/src/ast/ast.cpp:37
#9  0x000055555577d957 in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe5f0, binop=...)
[...]
```

**Comment by danobi** [comment]
I think this was fixed in 59d0b0d96e7
